# config/features.yaml
feature_extraction:
  task_classification:
    task_types: 
      - mmlu
      - gsm8k
      - hellaswag
      - winogrande
      - cnn_dailymail

    embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
    embedding_dim: 384
    instruction_max_length: 50
    classifier_path: "models/task_classifier.pkl"
    
  semantic_clustering:
    num_clusters: 3
    online_update: true
    centroids_path: "models/cluster_centroids.pkl"
    
  complexity:
    measure: "flesch_reading_ease"
    bins:
      - 0
      - 33
      - 67
    use_binned: true
    
  context_vector:
    one_hot_encode: true
    include_raw_embeddings: false
    normalize_numeric: true

feasibility:
  max_latency: 5