services:
  llm_db:
    image: postgres:15
    environment:
      POSTGRES_DB: llm_db
      POSTGRES_USER: tz
      POSTGRES_PASSWORD: hpc_llm
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "hpc_llm"]
    ports:
      - "6380:6379"

volumes:
  postgres_data: